import Fluent

/// Replaces email/password accounts with OAuth-only schema (github_id, login, avatar_url, email).
/// Drops and recreates accounts and all dependent tables. Data loss for existing accounts/projects.
struct AlterAccountsForOAuth: AsyncMigration {
    func prepare(on database: Database) async throws {
        // Drop in reverse dependency order
        try await database.schema("tools_index").delete()
        try await database.schema("skill_packages").delete()
        try await database.schema("request_logs").delete()
        try await database.schema("api_keys").delete()
        try await database.schema("auth_configs").delete()
        try await database.schema("repo_connections").delete()
        try await database.schema("releases").delete()
        try await database.schema("projects").delete()
        try await database.schema("accounts").delete()

        // Recreate accounts with OAuth schema
        try await database.schema("accounts")
            .id()
            .field("github_id", .int64, .required)
            .field("login", .string, .required)
            .field("avatar_url", .string)
            .field("email", .string)
            .field("created_at", .datetime)
            .unique(on: "github_id")
            .create()

        // Recreate projects
        try await database.schema("projects")
            .id()
            .field("account_id", .uuid, .required, .references("accounts", "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("slug", .string, .required)
            .field("subdomain", .string)
            .field("active_release_id", .uuid)
            .field("created_at", .datetime)
            .unique(on: "slug")
            .create()

        // Recreate dependent tables
        try await database.schema("repo_connections")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("provider", .string, .required)
            .field("repo_owner", .string, .required)
            .field("repo_name", .string, .required)
            .field("default_branch", .string, .required)
            .field("auth_type", .string, .required)
            .field("token_ref", .string)
            .field("webhook_id", .string)
            .field("created_at", .datetime)
            .create()

        try await database.schema("releases")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("commit_sha", .string, .required)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .field("error_summary", .string)
            .create()

        try await database.schema("skill_packages")
            .id()
            .field("release_id", .uuid, .required, .references("releases", "id", onDelete: .cascade))
            .field("path", .string, .required)
            .field("name", .string, .required)
            .field("description", .string)
            .field("hash", .string)
            .field("validation_status", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema("tools_index")
            .id()
            .field("skill_package_id", .uuid, .required, .references("skill_packages", "id", onDelete: .cascade))
            .field("tool_name", .string, .required)
            .field("schema_json", .string)
            .field("handler_type", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema("auth_configs")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("mode", .string, .required)
            .field("settings_json", .string)
            .field("created_at", .datetime)
            .create()

        try await database.schema("api_keys")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("key_prefix", .string, .required)
            .field("key_hash", .string, .required)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .field("last_used_at", .datetime)
            .create()

        try await database.schema("request_logs")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("release_id", .uuid, .references("releases", "id", onDelete: .setNull))
            .field("timestamp", .datetime)
            .field("client_id", .string)
            .field("method", .string, .required)
            .field("latency_ms", .int)
            .field("status", .string, .required)
            .field("error_code", .string)
            .create()
    }

    func revert(on database: Database) async throws {
        // Revert: drop new tables and recreate old schema
        try await database.schema("tools_index").delete()
        try await database.schema("skill_packages").delete()
        try await database.schema("request_logs").delete()
        try await database.schema("api_keys").delete()
        try await database.schema("auth_configs").delete()
        try await database.schema("repo_connections").delete()
        try await database.schema("releases").delete()
        try await database.schema("projects").delete()
        try await database.schema("accounts").delete()

        try await database.schema("accounts")
            .id()
            .field("email", .string, .required)
            .field("password_hash", .string, .required)
            .field("created_at", .datetime)
            .unique(on: "email")
            .create()

        try await database.schema("projects")
            .id()
            .field("account_id", .uuid, .required, .references("accounts", "id", onDelete: .cascade))
            .field("name", .string, .required)
            .field("slug", .string, .required)
            .field("subdomain", .string)
            .field("active_release_id", .uuid)
            .field("created_at", .datetime)
            .unique(on: "slug")
            .create()

        try await database.schema("repo_connections")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("provider", .string, .required)
            .field("repo_owner", .string, .required)
            .field("repo_name", .string, .required)
            .field("default_branch", .string, .required)
            .field("auth_type", .string, .required)
            .field("token_ref", .string)
            .field("webhook_id", .string)
            .field("created_at", .datetime)
            .create()

        try await database.schema("releases")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("commit_sha", .string, .required)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .field("error_summary", .string)
            .create()

        try await database.schema("skill_packages")
            .id()
            .field("release_id", .uuid, .required, .references("releases", "id", onDelete: .cascade))
            .field("path", .string, .required)
            .field("name", .string, .required)
            .field("description", .string)
            .field("hash", .string)
            .field("validation_status", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema("tools_index")
            .id()
            .field("skill_package_id", .uuid, .required, .references("skill_packages", "id", onDelete: .cascade))
            .field("tool_name", .string, .required)
            .field("schema_json", .string)
            .field("handler_type", .string, .required)
            .field("created_at", .datetime)
            .create()

        try await database.schema("auth_configs")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("mode", .string, .required)
            .field("settings_json", .string)
            .field("created_at", .datetime)
            .create()

        try await database.schema("api_keys")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("key_prefix", .string, .required)
            .field("key_hash", .string, .required)
            .field("status", .string, .required)
            .field("created_at", .datetime)
            .field("last_used_at", .datetime)
            .create()

        try await database.schema("request_logs")
            .id()
            .field("project_id", .uuid, .required, .references("projects", "id", onDelete: .cascade))
            .field("release_id", .uuid, .references("releases", "id", onDelete: .setNull))
            .field("timestamp", .datetime)
            .field("client_id", .string)
            .field("method", .string, .required)
            .field("latency_ms", .int)
            .field("status", .string, .required)
            .field("error_code", .string)
            .create()
    }
}
