import Fluent

struct AddPortableSkillRuntime: AsyncMigration {
    func prepare(on database: Database) async throws {
        // SQLite only supports one ADD COLUMN per ALTER TABLE; keep each additive change portable.
        try await database.schema(CompiledSkill.schema).field("canonical_schema_version", .int, .required, .sql(.default(1))).update()
        try await database.schema(CompiledSkill.schema).field("skill_id", .string).update()
        try await database.schema(CompiledSkill.schema).field("kind", .string).update()
        try await database.schema(CompiledSkill.schema).field("scope", .string).update()
        try await database.schema(CompiledSkill.schema).field("activation_mode", .string).update()
        try await database.schema(CompiledSkill.schema).field("enforcement", .string).update()
        try await database.schema(CompiledSkill.schema).field("priority", .int).update()
        try await database.schema(CompiledSkill.schema).field("version", .string).update()
        try await database.schema(CompiledSkill.schema).field("source_checksum", .string).update()
        try await database.schema(CompiledSkill.schema).field("canonical_json", .string).update()
        try await database.schema(CompiledSkill.schema).field("clarification_json", .string).update()
        try await database.schema(CompiledSkill.schema).field("clarification_required", .bool, .required, .sql(.default(true))).update()

        try await database.schema(SkillRuntimeOverride.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade))
            .field("repo_connection_id", .uuid, .references(RepoConnection.schema, "id", onDelete: .cascade))
            .field("skill_id", .string, .required).field("scope", .string, .required)
            .field("metadata_json", .string, .required).field("source_checksum", .string)
            .field("writeback_pr_url", .string).field("created_at", .datetime).field("updated_at", .datetime)
            .unique(on: "project_id", "repo_connection_id", "skill_id", "scope").create()
        try await database.schema(SkillAssignment.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade))
            .field("repo_connection_id", .uuid, .references(RepoConnection.schema, "id", onDelete: .cascade))
            .field("skill_id", .string, .required).field("scope", .string, .required)
            .field("activation_mode", .string, .required).field("required", .bool, .required)
            .field("priority", .int, .required).field("created_at", .datetime)
            .unique(on: "project_id", "repo_connection_id", "skill_id", "scope").create()
        try await database.schema(ProjectRuntimeSettings.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade)).unique(on: "project_id")
            .field("telemetry_enabled", .bool, .required, .sql(.default(false)))
            .field("telemetry_retention_days", .int, .required, .sql(.default(30)))
            .field("semantic_enabled", .bool, .required, .sql(.default(false)))
            .field("embedding_provider", .string).field("embedding_model", .string)
            .field("feedback_issue_creation_enabled", .bool, .required, .sql(.default(false)))
            .field("provider_preferences_json", .string).field("updated_at", .datetime).create()
        try await database.schema(SkillFeedbackRecord.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade))
            .field("skill_id", .string, .required).field("skill_version", .string, .required)
            .field("source_path", .string, .required).field("source_revision", .string)
            .field("category", .string, .required).field("summary", .string, .required)
            .field("evidence", .string).field("suggested_change", .string)
            .field("issue_draft_json", .string, .required).field("external_issue_url", .string)
            .field("created_at", .datetime).create()
        try await database.schema(SkillEmbeddingRecord.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade))
            .field("skill_id", .string, .required).field("source_checksum", .string, .required)
            .field("provider", .string, .required).field("model", .string, .required)
            .field("vector_json", .string, .required).field("created_at", .datetime)
            .unique(on: "project_id", "skill_id", "provider", "model", "source_checksum").create()
        try await database.schema(SkillRuntimeEvent.schema).id()
            .field("project_id", .uuid, .required, .references(Project.schema, "id", onDelete: .cascade))
            .field("trace_id", .uuid, .required).field("event_type", .string, .required)
            .field("skill_id", .string).field("reason_code", .string).field("score", .double)
            .field("request_hash", .string).field("detail_json", .string, .required).field("created_at", .datetime)
            .create()
    }

    func revert(on database: Database) async throws {
        try await database.schema(SkillRuntimeEvent.schema).delete()
        try await database.schema(SkillEmbeddingRecord.schema).delete()
        try await database.schema(SkillFeedbackRecord.schema).delete()
        try await database.schema(ProjectRuntimeSettings.schema).delete()
        try await database.schema(SkillAssignment.schema).delete()
        try await database.schema(SkillRuntimeOverride.schema).delete()
        try await database.schema(CompiledSkill.schema)
            .deleteField("canonical_schema_version").deleteField("skill_id").deleteField("kind")
            .deleteField("scope").deleteField("activation_mode").deleteField("enforcement")
            .deleteField("priority").deleteField("version").deleteField("source_checksum")
            .deleteField("canonical_json").deleteField("clarification_json").deleteField("clarification_required").update()
    }
}
